### ISSUE TITLE
Any advantage over Eloquent Resource conditional attributes?

### ISSUE THREAD

**Issue by k8n** [salomoni/authorized-attributes#6]
I discovered [this bit of Laravel](https://laravel.com/docs/5.6/eloquent-resources#conditional-attributes) which permits to do most of the same.

**Comment by k8n** [comment]
It may be worth a note in the docs.

**Comment by salomoni** [comment]
Thank you! Will add to the docs.

I'm wondering the benefits between using this package vs the API resources..
